### ISSUE TITLE
修改默认配置后报错

### ISSUE THREAD

**Issue by suxg001** [SpringForAll/spring-boot-starter-swagger#121]
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-11-06 14:18:26.565 [restartedMain] ERROR org.springframework.boot.SpringApplication - Application startup failed
org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: com.google.common.collect.FluentIterable.concat(Ljava/lang/Iterable;Ljava/lang/Iterable;)Lcom/google/common/collect/FluentIterable;
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)

**Comment by FictionDk** [comment]
使用yml的配置出现了同样的问题:
application-dev.yml
```yml
swagger: 
    enabled: true
    title: spring-boot-starter-swagger
    description: Starter for swagger 2.x
    version: 1.1.0.RELEASE
    license: Apache License, Version 2.0
    licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
    termsOfServiceUrl: https://github.com/dyc87112/spring-boot-starter-swagger
    contact.name: didi
    contact.url: http://blog.didispace.com
    contact.email: dyc87112@qq.com
    base-package: com.stpass.qmjk.demo
    
    global-operation-parameters:
        - name: access_token
          description: user access token
          modelRef: string
          parameterType: header
          required: true
        - name: timestamp
          description: access timestamp
          modelRef: int
          parameterType: header
          required: false
    apply-default-response-messages: true
    global-response-message: 
        get: 
            - code: 401
              message: 401get
            - code: 500
              message: 500get
              modelRef: ERROR
    ui-config:
        json-editor: false
        show-request-headers: true
        request-timeout: 5000
        submit-methods: get,delete  
```
