### ISSUE TITLE
请问这是缺少什么配置吗

### ISSUE THREAD

**Issue by marshalby2** [SpringForAll/spring-boot-starter-swagger#222]
Error creating bean with name 'createSpringFoxRestApi' defined in class path resource [com/spring4all/swagger/DocketConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [void]: Factory method 'createSpringFoxRestApi' threw exception; nested exception is java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "properties" is null

**Comment by wuyinq** [comment]
报的错一模一样

**Comment by zlclovetb** [comment]
和我报的错一样，从2.0.1.RELEASE降低至1.9.1.RELEASE就正常了，环境是springboot 2.5.6，flowable 6.7.0

**Comment by llin6025** [comment]
我看了下，确实是缺少了部分全局配置导致的，主要是：globalOperationParameters的全局配置
```yaml
logging:
  level:
    root: debug

spring:
  application:
    name: swagger-demo-issue-221

springfox:
  documentation:
    enabled: true
swagger:
  globalOperationParameters:
    -
        name: timestamp
        description: access timestamp
        modelRef: integer
        parameterType: header
        required: false
  base-package: 'com.example'
  base-path: '/**'
  exclude-path: '/error, /ops/**'
  title: '注解方式的Swagger'
  description: '这是注解方式的Swagger'
  version: '2.0.1.RELEASE'
  license-url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  license: 'The Apache License'
  contact:
    name: '吕小白'
    url: 'https:www.baidu.com'
    email: '******@qq.com'

  host: localhost:8080
```
